function [ profileArray, profileTimetable ] = processPowerProfile( ...
    dataAnnual, startTime, horizonHours, timeStep ...
    )
% pvProfile - create a sample daily pv profile from annual data 
%   dataAnnual [timetable]: Power Profile (kW) such that average would be 
%       the method of resampling 
%   startTime [str]: timestamp of the desired start time
%   horizonHours [int]: the length of the horizon (in hours)
%   timeStep [int]: the time step in seconds 

    range2extract = timerange( ...
        datetime(startTime), ...
        datetime(startTime) + hours(horizonHours), ...
        'openright' ...
        );
    
    originalTimeStep = dataAnnual.Properties.TimeStep;
    newTimeStep = seconds(timeStep);

    if originalTimeStep < newTimeStep 
        profileTimetable = retime( ...
            dataAnnual(range2extract, :), 'regular', 'mean', ...
            'TimeStep', newTimeStep ...
            );
    elseif originalTimeStep > newTimeStep
        profileTimetable = retime( ...
            dataAnnual(range2extract, :), 'regular', 'previous', ...
            'TimeStep', newTimeStep ...
            );
    else
        profileTimetable = dataAnnual(range2extract, :);
    end
    
    profileArray = profileTimetable.Variables;
end